const products = [
    {
      "id": "prod-1",
      "name": "Wireless Bluetooth Headphones",
      "category": "electronics",
      "price": 2500,
      "colors": ["black", "white", "blue"],
      "sizes": [],
      "rating": 4,
      "reviews": 1200,
      "image": "https://images.unsplash.com/photo-1505739718967-6df30ff369c7?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHdpcmVsZXNzJTIwYmx1ZXRvb3RoJTIwaGVhZHBob25lc3xlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-2",
      "name": "Smart Fitness Tracker",
      "category": "electronics",
      "price": 4200,
      "colors": ["black", "pink", "blue"],
      "sizes": [],
      "rating": 4.2,
      "reviews": 6000,
      "image": "https://images.unsplash.com/photo-1620213391117-0d169a917221?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Rml0bmVzcyUyMFRyYWNrZXJ8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-3",
      "name": "Organic Cotton T-Shirt",
      "category": "clothing",
      "price": 460,
      "colors": ["white", "black", "gray", "red"],
      "sizes": ["S", "M", "L", "XL"],
      "rating": 4.0,
      "reviews": 450,
      "image": "https://images.unsplash.com/photo-1713881587420-113c1c43e28a?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8T3JnYW5pYyUyMENvdHRvbiUyMFQlMjBTaGlydHxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-4",
      "name": "Stainless Steel Water Bottle",
      "category": "home",
      "price": 350,
      "colors": ["silver", "black", "blue"],
      "sizes": [],
      "rating": 4.7,
      "reviews": 4200,
      "image": "https://images.unsplash.com/photo-1620304386414-267c83b1857a?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fFN0YWlubGVzcyUyMFN0ZWVsJTIwV2F0ZXIlMjBCb3R0bGV8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-5",
      "name": "Wireless Charging Pad",
      "category": "electronics",
      "price": 1999,
      "colors": ["white", "black"],
      "sizes": [],
      "rating": 4.3,
      "reviews": 928,
      "image": "https://images.unsplash.com/photo-1543472750-506bacbf5808?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V2lyZWxlc3MlMjBDaGFyZ2luZyUyMFBhZHxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-6",
      "name": "Men's Slim Fit Jeans",
      "category": "clothing",
      "price": 640,
      "colors": ["blue", "black"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.3,
      "reviews": 1280,
      "image": "https://images.unsplash.com/photo-1555689502-c4b22d76c56f?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWVuJ3MlMjBTbGltJTIwRml0JTIwSmVhbnN8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-7",
      "name": "Portable Power Bank",
      "category": "electronics",
      "price": 999,
      "colors": ["black", "silver", "red"],
      "sizes": [],
      "rating": 4.4,
      "reviews": 150,
      "image": "https://images.unsplash.com/photo-1585995603413-eb35b5f4a50b?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8UG93ZXIlMjBCYW5rfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-8",
      "name": "Women’s Running Shoes",
      "category": "clothing",
      "price": 799,
      "colors": ["black", "pink", "white"],
      "sizes": ["5", "6", "7", "8", "9"],
      "rating": 4.6,
      "reviews": 1502,
      "image": "https://images.unsplash.com/photo-1557161187-634f1a92a569?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8V29tZW4lRTIlODAlOTlzJTIwUnVubmluZyUyMFNob2VzfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-9",
      "name": "Ceramic Non-Stick Pan",
      "category": "home",
      "price": 399,
      "colors": ["black", "green"],
      "sizes": [],
      "rating": 4.8,
      "reviews": 1759,
      "image": "https://images.unsplash.com/photo-1688399104634-61a524f623ed?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Tm9uJTIwU3RpY2slMjBQYW58ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-10",
      "name": "Noise-Cancelling Earbuds",
      "category": "electronics",
      "price": 999,
      "colors": ["black", "white"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 2500,
      "image": "https://images.unsplash.com/photo-1615281612781-4b972bd4e3fe?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8RWFyYnVkc3xlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-11",
      "name": "Men’s Leather Jacket",
      "category": "clothing",
      "price": 1499,
      "colors": ["black", "brown"],
      "sizes": ["M", "L", "XL"],
      "rating": 4.3,
      "reviews": 899,
      "image": "https://images.unsplash.com/photo-1727515192207-3dc860bfd773?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8TWVuJUUyJTgwJTk5cyUyMExlYXRoZXIlMjBKYWNrZXR8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-12",
      "name": "Smart LED Bulb",
      "category": "home",
      "price": 1499,
      "colors": ["white"],
      "sizes": [],
      "rating": 4.2,
      "reviews": 650,
      "image": "https://images.unsplash.com/photo-1532007271951-c487760934ae?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TEVEJTIwQnVsYnxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-13",
      "name": "Gaming Mouse",
      "category": "electronics",
      "price": 5999,
      "colors": ["black", "red"],
      "sizes": [],
      "rating": 4.7,
      "reviews": 534,
      "image": "https://images.unsplash.com/photo-1613141412501-9012977f1969?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8R2FtaW5nJTIwTW91c2V8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-14",
      "name": "Women’s Yoga Pants",
      "category": "clothing",
      "price": 699,
      "colors": ["black", "navy", "gray"],
      "sizes": ["XS", "S", "M", "L"],
      "rating": 4.4,
      "reviews": 777,
      "image": "https://images.unsplash.com/photo-1633707079221-63b0b83f9b87?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V29tZW4lRTIlODAlOTlzJTIwWW9nYSUyMFBhbnRzfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-15",
      "name": "Glass Food Storage Set",
      "category": "home",
      "price": 499,
      "colors": ["clear"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 120,
      "image": "https://plus.unsplash.com/premium_photo-1721199112826-40f35ebcb7a0?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8R2xhc3MlMjBGb29kJTIwU3RvcmFnZSUyMFNldHxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-16",
      "name": "4K Action Camera",
      "category": "electronics",
      "price": 1299,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 95,
      "image": "https://images.unsplash.com/photo-1690176483702-7ee397871388?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8NEslMjBBY3Rpb24lMjBDYW1lcmF8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-17",
      "name": "Knit Sweater",
      "category": "clothing",
      "price": 499,
      "colors": ["blue", "gray", "white"],
      "sizes": ["S", "M", "L"],
      "rating": 4.3,
      "reviews": 550,
      "image": "https://images.unsplash.com/photo-1631541909061-71e349d1f203?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8S25pdCUyMFN3ZWF0ZXJ8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-18",
      "name": "Electric Kettle",
      "category": "home",
      "price": 1399,
      "colors": ["silver", "black"],
      "sizes": [],
      "rating": 4.8,
      "reviews": 180,
      "image": "https://images.unsplash.com/photo-1643114786355-ff9e52736eab?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8RWxlY3RyaWMlMjBLZXR0bGV8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-19",
      "name": "Wireless Keyboard",
      "category": "electronics",
      "price": 699,
      "colors": ["black", "white"],
      "sizes": [],
      "rating": 4.4,
      "reviews": 810,
      "image": "https://images.unsplash.com/photo-1694405156884-dea1ffb40ede?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8V2lyZWxlc3MlMjBLZXlib2FyZHxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-20",
      "name": "Denim Jacket",
      "category": "clothing",
      "price": 6999,
      "colors": ["blue", "black"],
      "sizes": ["S", "M", "L", "XL"],
      "rating": 4.2,
      "reviews": 1562,
      "image": "https://images.unsplash.com/photo-1519803786820-8f866133444d?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8RGVuaW0lMjBKYWNrZXR8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-21",
      "name": "Bamboo Cutting Board",
      "category": "home",
      "price": 299,
      "colors": ["natural"],
      "sizes": [],
      "rating": 4.7,
      "reviews": 14800,
      "image": "https://images.unsplash.com/photo-1660002561318-6ef0a0ae1f04?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8QmFtYm9vJTIwQ3V0dGluZyUyMEJvYXJkfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-22",
      "name": "Portable Bluetooth Speaker",
      "category": "electronics",
      "price": 599,
      "colors": ["black", "blue", "red"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 865,
      "image": "https://images.unsplash.com/photo-1518671678551-911467efe539?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Qmx1ZXRvb3RoJTIwU3BlYWtlcnxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-23",
      "name": "Women’s Casual Dress",
      "category": "clothing",
      "price": 460,
      "colors": ["black", "red", "blue"],
      "sizes": ["S", "M", "L"],
      "rating": 4.3,
      "reviews": 1488,
      "image": "https://plus.unsplash.com/premium_photo-1682093104886-8833953cf2c8?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8V29tZW4lRTIlODAlOTlzJTIwQ2FzdWFsJTIwRHJlc3N8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-24",
      "name": "Air Purifier",
      "category": "home",
      "price": 32000,
      "colors": ["white"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 130,
      "image": "https://images.unsplash.com/photo-1632928274371-878938e4d825?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8QWlyJTIwUHVyaWZpZXJ8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-25",
      "name": "Smart Doorbell",
      "category": "electronics",
      "price": 6000,
      "colors": ["black", "silver"],
      "sizes": [],
      "rating": 4.4,
      "reviews": 1205,
      "image": "https://images.unsplash.com/photo-1633194883650-df448a10d554?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8RG9vcmJlbGx8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-26",
      "name": "Men’s Polo Shirt",
      "category": "clothing",
      "price": 2999,
      "colors": ["white", "blue", "black"],
      "sizes": ["S", "M", "L", "XL"],
      "rating": 4.2,
      "reviews": 780,
      "image": "https://images.unsplash.com/photo-1572627286668-91c19b41b891?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8TWVuJUUyJTgwJTk5cyUyMFBvbG8lMjBTaGlydHxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-27",
      "name": "Silicone Baking Mat",
      "category": "home",
      "price": 199,
      "colors": ["red", "black"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 995,
      "image": "https://images.unsplash.com/photo-1598968333180-9b4f6bc2bf52?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8QmFraW5nJTIwTWF0fGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-28",
      "name": "Smart Thermostat",
      "category": "electronics",
      "price": 7999,
      "colors": ["white", "black"],
      "sizes": [],
      "rating": 4.7,
      "reviews": 220,
      "image": "https://images.unsplash.com/photo-1545259741-2ea3ebf61fa3?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U21hcnQlMjBUaGVybW9zdGF0fGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-29",
      "name": "Women’s Scarf",
      "category": "clothing",
      "price": 499,
      "colors": ["red", "blue", "gray"],
      "sizes": [],
      "rating": 4.3,
      "reviews": 12650,
      "image": "https://images.unsplash.com/photo-1674165064267-1ee193c0c14a?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V29tZW4lRTIlODAlOTlzJTIwU2NhcmZ8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-30",
      "name": "Cast Iron Skillet",
      "category": "home",
      "price": 499,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.8,
      "reviews": 690,
      "image": "https://images.unsplash.com/photo-1591745952765-071aa8677b2b?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q2FzdCUyMElyb24lMjBTa2lsbGV0fGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-31",
      "name": "Wireless Security Camera",
      "category": "electronics",
      "price": 8999,
      "colors": ["white", "black"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 1125,
      "image": "https://images.unsplash.com/photo-1724343025504-3afb6d67566b?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V2lyZWxlc3MlMjBTZWN1cml0eSUyMENhbWVyYXxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-32",
      "name": "Men’s Hoodie",
      "category": "clothing",
      "price": 3999,
      "colors": ["black", "gray", "blue"],
      "sizes": ["S", "M", "L", "XL"],
      "rating": 4.4,
      "reviews": 885,
      "image": "https://images.unsplash.com/photo-1697289462507-1f133d023277?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fE1lbiVFMiU4MCU5OXMlMjBIb29kaWV8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-33",
      "name": "Reusable Coffee Mug",
      "category": "home",
      "price": 99,
      "colors": ["white", "black", "blue"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 18700,
      "image": "https://images.unsplash.com/photo-1533776992670-a72f4c28235e?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q29mZmVlJTIwTXVnfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-34",
      "name": "Smart Watch",
      "category": "electronics",
      "price": 12999,
      "colors": ["black", "silver"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 1480,
      "image": "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U21hcnQlMjBXYXRjaHxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-35",
      "name": "Women’s Blouse",
      "category": "clothing",
      "price": 2499,
      "colors": ["white", "blue", "red"],
      "sizes": ["S", "M", "L"],
      "rating": 4.3,
      "reviews": 680,
      "image": "https://images.unsplash.com/photo-1564139676155-afc1bb95745c?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V29tZW4lRTIlODAlOTlzJTIwQmxvdXNlfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-36",
      "name": "Digital Meat Thermometer",
      "category": "home",
      "price": 999,
      "colors": ["black", "silver"],
      "sizes": [],
      "rating": 4.7,
      "reviews": 195,
      "image": "https://images.unsplash.com/photo-1695048441307-d081dbd2b5a8?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8RGlnaXRhbCUyME1lYXQlMjBUaGVybW9tZXRlcnxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-37",
      "name": "Bluetooth FM Transmitter",
      "category": "electronics",
      "price": 2499,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.4,
      "reviews": 80,
      "image": "https://images.unsplash.com/photo-1592919347498-69564e361791?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fEZNJTIwVHJhbnNtaXR0ZXJ8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-38",
      "name": "Men’s Dress Shirt",
      "category": "clothing",
      "price": 499,
      "colors": ["white", "blue"],
      "sizes": ["S", "M", "L", "XL"],
      "rating": 4.2,
      "reviews": 785,
      "image": "https://images.unsplash.com/photo-1666358085449-a10a39f33942?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8TWVuJUUyJTgwJTk5cyUyMERyZXNzJTIwU2hpcnR8ZW58MHx8MHx8fDA%3Dt",
      "inStock": true
    },
    {
      "id": "prod-39",
      "name": "Wooden Salad Bowl",
      "category": "home",
      "price": 199,
      "colors": ["natural"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 890,
      "image": "https://images.unsplash.com/photo-1613746190970-a2f2a0fcd8aa?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V29vZGVuJTIwU2FsYWQlMjBCb3dsfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-40",
      "name": "USB-C Hub",
      "category": "electronics",
      "price": 399,
      "colors": ["silver", "black"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 1810,
      "image": "https://images.unsplash.com/photo-1616578781650-cd818fa41e57?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8VVNCJTIwQyUyMEh1YnxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-41",
      "name": "Women’s Winter Coat",
      "category": "clothing",
      "price": 2899,
      "colors": ["black", "gray"],
      "sizes": ["S", "M", "L"],
      "rating": 4.4,
      "reviews": 895,
      "image": "https://images.unsplash.com/photo-1694024313710-0505d80467e3?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V29tZW4lRTIlODAlOTlzJTIwV2ludGVyJTIwQ29hdHxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-42",
      "name": "Ceramic Plant Pot",
      "category": "home",
      "price": 299,
      "colors": ["white", "blue"],
      "sizes": [],
      "rating": 4.3,
      "reviews": 1570,
      "image": "https://images.unsplash.com/photo-1629380321590-3b3f75d66dec?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q2VyYW1pYyUyMFBsYW50JTIwUG90fGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-43",
      "name": "Wireless Game Controller",
      "category": "electronics",
      "price": 3999,
      "colors": ["black", "white"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 1930,
      "image": "https://images.unsplash.com/photo-1662355516417-202c7aca5109?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V2lyZWxlc3MlMjBHYW1lJTIwQ29udHJvbGxlcnxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-44",
      "name": "Men’s Athletic Shorts",
      "category": "clothing",
      "price": 2599,
      "colors": ["black", "gray", "blue"],
      "sizes": ["S", "M", "L"],
      "rating": 4.3,
      "reviews": 965,
      "image": "https://images.unsplash.com/photo-1695918428860-a3bc6a2f1d4b?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWVuJUUyJTgwJTk5cyUyMEF0aGxldGljJTIwU2hvcnRzfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-45",
      "name": "Stainless Steel Cutlery Set",
      "category": "home",
      "price": 399,
      "colors": ["silver"],
      "sizes": [],
      "rating": 4.7,
      "reviews": 850,
      "image": "https://images.unsplash.com/photo-1689269212544-6235c671441c?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8U3RhaW5sZXNzJTIwU3RlZWwlMjBDdXRsZXJ5JTIwU2V0fGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-46",
      "name": "Mini Projector",
      "category": "electronics",
      "price": 12499,
      "colors": ["black", "white"],
      "sizes": [],
      "rating": 4.4,
      "reviews": 600,
      "image": "https://images.unsplash.com/photo-1535016120720-40c646be5580?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWluaSUyMFByb2plY3RvcnxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-47",
      "name": "Women’s Leather Belt",
      "category": "clothing",
      "price": 499,
      "colors": ["black", "brown"],
      "sizes": ["S", "M", "L"],
      "rating": 4.2,
      "reviews": 595,
      "image": "https://images.unsplash.com/photo-1734383524180-3c6f9b21e8e3?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V29tZW4lRTIlODAlOTlzJTIwTGVhdGhlciUyMEJlbHR8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-48",
      "name": "Non-Slip Yoga Mat",
      "category": "home",
      "price": 1199,
      "colors": ["blue", "purple"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 8120,
      "image": "https://images.unsplash.com/photo-1661308411865-4fce7576bef8?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Tm9uJTIwU2xpcCUyMFlvZ2ElMjBNYXR8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-49",
      "name": "Smart Plug",
      "category": "electronics",
      "price": 1499,
      "colors": ["white"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 90,
      "image": "https://images.unsplash.com/photo-1588422273146-c799447ccb81?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8U21hcnQlMjBQbHVnfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-50",
      "name": "Men’s Baseball Cap",
      "category": "clothing",
      "price": 399,
      "colors": ["black", "blue", "gray"],
      "sizes": [],
      "rating": 4.3,
      "reviews": 8260,
      "image": "https://images.unsplash.com/photo-1587493681629-6b4c02555fee?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWVuJUUyJTgwJTk5cyUyMEJhc2ViYWxsJTIwQ2FwfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-51",
      "name": "Glass Pitcher",
      "category": "home",
      "price": 899,
      "colors": ["clear"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 580,
      "image": "https://images.unsplash.com/photo-1659290823182-9be2fc4834dc?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8R2xhc3MlMjBQaXRjaGVyfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-52",
      "name": "Wireless Car Charger",
      "category": "electronics",
      "price": 2499,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.4,
      "reviews": 4285,
      "image": "https://images.unsplash.com/photo-1600490819528-42405785433a?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8V2lyZWxlc3MlMjBDYXIlMjBDaGFyZ2VyfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-53",
      "name": "Women’s Sneakers",
      "category": "clothing",
      "price": 2150,
      "colors": ["white", "black", "pink"],
      "sizes": ["5", "6", "7", "8"],
      "rating": 4.5,
      "reviews": 1810,
      "image": "https://images.unsplash.com/photo-1633119114616-fdd876d61374?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8V29tZW4lRTIlODAlOTlzJTIwU25lYWtlcnN8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-54",
      "name": "Electric Toothbrush",
      "category": "home",
      "price": 799,
      "colors": ["white", "black"],
      "sizes": [],
      "rating": 4.7,
      "reviews": 1640,
      "image": "https://images.unsplash.com/photo-1553091844-4204b59e3661?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8RWxlY3RyaWMlMjBUb290aGJydXNofGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-55",
      "name": "Foldable Drone",
      "category": "electronics",
      "price": 52999,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 120,
      "image": "https://images.unsplash.com/photo-1739742465286-a48290c94375?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Rm9sZGFibGUlMjBEcm9uZXxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-56",
      "name": "Men’s Chinos",
      "category": "clothing",
      "price": 999,
      "colors": ["navy", "khaki"],
      "sizes": ["30", "32", "34"],
      "rating": 4.3,
      "reviews": 750,
      "image": "https://images.unsplash.com/photo-1499202977705-65f436dac18a?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Q2hpbm9zfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-57",
      "name": "Ceramic Mug Set",
      "category": "home",
      "price": 399,
      "colors": ["white", "blue"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 1200,
      "image": "https://images.unsplash.com/photo-1703621422899-4c0a495f8d92?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Q2VyYW1pYyUyME11ZyUyMFNldHxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-58",
      "name": "Portable SSD",
      "category": "electronics",
      "price": 2999,
      "colors": ["black", "silver"],
      "sizes": [],
      "rating": 4.7,
      "reviews": 1850,
      "image": "https://images.unsplash.com/photo-1719937050792-a6a15d899281?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8UG9ydGFibGUlMjBTU0R8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-59",
      "name": "Women’s Cardigan",
      "category": "clothing",
      "price": 399,
      "colors": ["gray", "black", "white"],
      "sizes": ["S", "M", "L"],
      "rating": 4.4,
      "reviews": 80,
      "image": "https://images.unsplash.com/photo-1713017521422-31a89021432c?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8V29tZW4lRTIlODAlOTlzJTIwQ2FyZGlnYW58ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-60",
      "name": "Stainless Steel Mixing Bowl",
      "category": "home",
      "price": 499,
      "colors": ["silver"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 790,
      "image": "https://images.unsplash.com/photo-1651928692978-8462ae8d1270?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8U3RhaW5sZXNzJTIwU3RlZWwlMjBNaXhpbmclMjBCb3dsfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-61",
      "name": "Wireless Router",
      "category": "electronics",
      "price": 2499,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.4,
      "reviews": 1610,
      "image": "https://images.unsplash.com/photo-1681383064412-171e5bee5f6e?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V2lyZWxlc3MlMjBSb3V0ZXJ8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-62",
      "name": "Men’s Bomber Jacket",
      "category": "clothing",
      "price": 1499,
      "colors": ["black", "green"],
      "sizes": ["M", "L", "XL"],
      "rating": 4.3,
      "reviews": 245,
      "image": "https://images.unsplash.com/photo-1548883354-a3fb8460973f?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8TWVuJUUyJTgwJTk5cyUyMEJvbWJlciUyMEphY2tldHxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-63",
      "name": "Silicone Spatula Set",
      "category": "home",
      "price": 1799,
      "colors": ["black", "red"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 85,
      "image": "https://images.unsplash.com/photo-1613206485477-34b2b17fa93f?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8U2lsaWNvbmUlMjBTcGF0dWxhJTIwU2V0fGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-64",
      "name": "Smart Light Strip",
      "category": "electronics",
      "price": 599,
      "colors": ["white"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 8595,
      "image": "https://images.unsplash.com/photo-1690017595298-4ba907322a0d?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TGlnaHQlMjBTdHJpcHxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-65",
      "name": "Women’s Ankle Boots",
      "category": "clothing",
      "price": 1699,
      "colors": ["black", "brown"],
      "sizes": ["6", "7", "8"],
      "rating": 4.4,
      "reviews": 190,
      "image": "https://plus.unsplash.com/premium_photo-1671718111684-9142a70a5fe0?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8V29tZW4lRTIlODAlOTlzJTIwQW5rbGUlMjBCb290c3xlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-66",
      "name": "Bamboo Toothbrush Set",
      "category": "home",
      "price": 99,
      "colors": ["natural"],
      "sizes": [],
      "rating": 4.3,
      "reviews": 28570,
      "image": "https://images.unsplash.com/photo-1591184510248-6be5138855a0?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8QmFtYm9vJTIwVG9vdGhicnVzaHxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-67",
      "name": "Portable Monitor",
      "category": "electronics",
      "price": 2990,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 120,
      "image": "https://images.unsplash.com/photo-1709536777126-238639005f7a?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8UG9ydGFibGUlMjBNb25pdG9yfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-68",
      "name": "Men’s Swim Trunks",
      "category": "clothing",
      "price": 299,
      "colors": ["blue", "red"],
      "sizes": ["S", "M", "L"],
      "rating": 4.2,
      "reviews": 860,
      "image": "https://images.unsplash.com/photo-1423594390679-b5d9611e1a2f?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U3dpbSUyMFRydW5rc3xlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-69",
      "name": "Glass Baking Dish",
      "category": "home",
      "price": 399,
      "colors": ["clear"],
      "sizes": [],
      "rating": 4.7,
      "reviews": 1700,
      "image": "https://images.unsplash.com/photo-1552349874-a2228092ec42?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8R2xhc3MlMjBCYWtpbmclMjBEaXNofGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-70",
      "name": "Wireless Webcam",
      "category": "electronics",
      "price": 2499,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 1710,
      "image": "https://images.unsplash.com/photo-1728971975421-50f3dc9663a4?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V2lyZWxlc3MlMjBXZWJjYW18ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-71",
      "name": "Women’s Tote Bag",
      "category": "clothing",
      "price": 49.99,
      "colors": ["black", "brown"],
      "sizes": [],
      "rating": 4.4,
      "reviews": 85,
      "image": "https://images.unsplash.com/photo-1654111081532-68b96326f24f?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8V29tZW4lRTIlODAlOTlzJTIwVG90ZSUyMEJhZ3xlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-72",
      "name": "Stainless Steel Straw Set",
      "category": "home",
      "price": 99,
      "colors": ["silver"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 8490,
      "image": "https://images.unsplash.com/photo-1526636968706-169f89dcab64?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8U3RhaW5sZXNzJTIwU3RlZWwlMjBTdHJhdyUyMFNldHxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-73",
      "name": "Bluetooth Tracker",
      "category": "electronics",
      "price": 3299,
      "colors": ["black", "white"],
      "sizes": [],
      "rating": 4.3,
      "reviews": 380,
      "image": "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c21hcnQlMjB3YXRjaHxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-74",
      "name": "Men’s Leather Wallet",
      "category": "clothing",
      "price": 1299,
      "colors": ["black", "brown"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 2595,
      "image": "https://images.unsplash.com/photo-1651928692943-5d837fccf061?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWVuJUUyJTgwJTk5cyUyMExlYXRoZXIlMjBXYWxsZXR8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-75",
      "name": "Ceramic Dinner Plate Set",
      "category": "home",
      "price": 2399,
      "colors": ["white"],
      "sizes": [],
      "rating": 4.7,
      "reviews": 18220,
      "image": "https://images.unsplash.com/photo-1677336037712-c620a0d977ff?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q2VyYW1pYyUyMERpbm5lciUyMFBsYXRlJTIwU2V0fGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-76",
      "name": "Smart Scale",
      "category": "electronics",
      "price": 499,
      "colors": ["black", "white"],
      "sizes": [],
      "rating": 4.4,
      "reviews": 700,
      "image": "https://images.unsplash.com/photo-1716698286313-9a2349d41110?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8U21hcnQlMjBTY2FsZXxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-77",
      "name": "Women’s Sunglasses",
      "category": "clothing",
      "price": 2680,
      "colors": ["black", "brown"],
      "sizes": [],
      "rating": 4.3,
      "reviews": 1270,
      "image": "https://images.unsplash.com/photo-1707672972137-64390186af62?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8V29tZW4lRTIlODAlOTlzJTIwU3VuZ2xhc3Nlc3xlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-78",
      "name": "Wooden Coaster Set",
      "category": "home",
      "price": 1499,
      "colors": ["natural"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 80,
      "image": "https://images.unsplash.com/photo-1611841528417-6227ffbca5ee?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8V29vZGVuJTIwQ29hc3RlciUyMFNldHxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-79",
      "name": "Wireless Barcode Scanner",
      "category": "electronics",
      "price": 7999,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 90,
      "image": "https://images.unsplash.com/photo-1623511907283-2803370a1642?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8V2lyZWxlc3MlMjBCYXJjb2RlJTIwU2Nhbm5lcnxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-80",
      "name": "Men’s Tie",
      "category": "clothing",
      "price": 199,
      "colors": ["blue", "red"],
      "sizes": [],
      "rating": 4.2,
      "reviews": 60,
      "image": "https://images.unsplash.com/photo-1745270008562-318fb7dbfe1a?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8TWVuJUUyJTgwJTk5cyUyMFRpZXxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-81",
      "name": "Silicone Ice Tray",
      "category": "home",
      "price": 99,
      "colors": ["blue", "black"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 75,
      "image": "https://images.unsplash.com/photo-1647325207539-8dfa0070dfcd?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U2lsaWNvbmUlMjBJY2UlMjBUcmF5U2lsaWNvbmUlMjBJY2UlMjBUcmF5fGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-82",
      "name": "Smart Smoke Detector",
      "category": "electronics",
      "price": 6599,
      "colors": ["white"],
      "sizes": [],
      "rating": 4.7,
      "reviews": 110,
      "image": "https://images.unsplash.com/photo-1733751682955-87f788d3b910?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8U21hcnQlMjBTbW9rZSUyMERldGVjdG9yfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-83",
      "name": "Women’s Skirt",
      "category": "clothing",
      "price": 399,
      "colors": ["black", "blue"],
      "sizes": ["S", "M", "L"],
      "rating": 4.3,
      "reviews": 65,
      "image": "https://images.unsplash.com/photo-1556747439-3b96858b9d8d?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V29tZW4lRTIlODAlOTlzJTIwU2tpcnR8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-84",
      "name": "Stainless Steel Colander",
      "category": "home",
      "price": 499,
      "colors": ["silver"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 485,
      "image": "https://images.unsplash.com/photo-1700515268370-ac596e44dfe5?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8U3RhaW5sZXNzJTIwU3RlZWwlMjBDb2xhbmRlcnxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-85",
      "name": "Wireless Presenter",
      "category": "electronics",
      "price": 2299,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.4,
      "reviews": 810,
      "image": "https://images.unsplash.com/photo-1629603819085-aaca50d00443?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fFdpcmVsZXNzJTIwUHJlc2VudGVyfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-86",
      "name": "Men’s Sandals",
      "category": "clothing",
      "price": 399,
      "colors": ["black", "brown"],
      "sizes": ["8", "9", "10"],
      "rating": 4.3,
      "reviews": 70,
      "image": "https://images.unsplash.com/photo-1672668799542-1c13fbe494c7?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8TWVuJUUyJTgwJTk5cyUyMFNhbmRhbHN8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-87",
      "name": "Ceramic Vase",
      "category": "home",
      "price": 499,
      "colors": ["white", "blue"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 90,
      "image": "https://images.unsplash.com/photo-1597696929736-6d13bed8e6a8?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q2VyYW1pYyUyMFZhc2V8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-88",
      "name": "Smart Sprinkler Controller",
      "category": "electronics",
      "price": 2999,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 100,
      "image": "https://images.unsplash.com/photo-1714632429418-68d8e396fbd6?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U21hcnQlMjBTcHJpbmtsZXIlMjBDb250cm9sbGVyfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-89",
      "name": "Women’s Pajamas",
      "category": "clothing",
      "price": 299,
      "colors": ["blue", "pink"],
      "sizes": ["S", "M", "L"],
      "rating": 4.4,
      "reviews": 75,
      "image": "https://images.unsplash.com/photo-1693987654444-9758f84278f0?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V29tZW4lRTIlODAlOTlzJTIwUGFqYW1hc3xlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-90",
      "name": "Wooden Spice Rack",
      "category": "home",
      "price": 399,
      "colors": ["natural"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 85,
      "image": "https://images.unsplash.com/photo-1744329630135-06bb9d5e02a0?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V29vZGVuJTIwU3BpY2UlMjBSYWNrfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-91",
      "name": "Wireless Microphone",
      "category": "electronics",
      "price": 599,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.4,
      "reviews": 90,
      "image": "https://images.unsplash.com/photo-1683304554869-8a871c913096?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V2lyZWxlc3MlMjBNaWNyb3Bob25lfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-92",
      "name": "Men’s Vest",
      "category": "clothing",
      "price": 4999,
      "colors": ["black", "gray"],
      "sizes": ["M", "L", "XL"],
      "rating": 4.3,
      "reviews": 70,
      "image": "https://images.unsplash.com/photo-1638104977265-8e8ea24aa2aa?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8TWVuJUUyJTgwJTk5cyUyMFZlc3R8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-93",
      "name": "Glass Candle Holder",
      "category": "home",
      "price": 199,
      "colors": ["clear"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 80,
      "image": "https://images.unsplash.com/photo-1693728587329-f7d953e7d84b?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8R2xhc3MlMjBDYW5kbGUlMjBIb2xkZXJ8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-94",
      "name": "Smart Garage Door Opener",
      "category": "electronics",
      "price": 12999,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 110,
      "image": "https://images.unsplash.com/photo-1680768805827-3a3227dd1176?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U21hcnQlMjBHYXJhZ2UlMjBEb29yJTIwT3BlbmVyfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-95",
      "name": "Women’s Hat",
      "category": "clothing",
      "price": 299,
      "colors": ["black", "beige"],
      "sizes": [],
      "rating": 4.3,
      "reviews": 65,
      "image": "https://images.unsplash.com/photo-1629381565767-1ca9943b98cb?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V29tZW4lRTIlODAlOTlzJTIwSGF0fGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-96",
      "name": "Stainless Steel Toaster",
      "category": "home",
      "price": 999,
      "colors": ["silver"],
      "sizes": [],
      "rating": 4.7,
      "reviews": 120,
      "image": "https://images.unsplash.com/photo-1740803292814-13d2e35924c3?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U3RhaW5sZXNzJTIwU3RlZWwlMjBUb2FzdGVyfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-97",
      "name": "Wireless Charging Stand",
      "category": "electronics",
      "price": 399,
      "colors": ["black", "white"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 100,
      "image": "https://images.unsplash.com/photo-1617975316514-69cd7e16c2a4?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V2lyZWxlc3MlMjBDaGFyZ2luZyUyMFN0YW5kfGVufDB8fDB8fHww",
      "inStock": true
    },
    {
      "id": "prod-98",
      "name": "Men’s Gloves",
      "category": "clothing",
      "price": 599,
      "colors": ["black", "brown"],
      "sizes": ["M", "L"],
      "rating": 4.3,
      "reviews": 60,
      "image": "https://images.unsplash.com/photo-1733652220367-367b63bd68fb?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWVuJUUyJTgwJTk5cyUyMEdsb3Zlc3xlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-99",
      "name": "Ceramic Soap Dispenser",
      "category": "home",
      "price": 399,
      "colors": ["white", "gray"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 85,
      "image": "https://images.unsplash.com/photo-1698724534662-996c71b2d3c8?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Q2VyYW1pYyUyMFNvYXAlMjBEaXNwZW5zZXJ8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-100",
      "name": "Smart Pet Feeder",
      "category": "electronics",
      "price": 799,
      "colors": ["white"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 105,
      "image": "https://images.unsplash.com/photo-1714068691210-073dc52c6c1d?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8U21hcnQlMjBQZXQlMjBGZWVkZXJ8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-101",
      "name": "Men's Relaxed Fit Jeans",
      "category": "clothing",
      "price": 5299,
      "colors": ["dark blue", "black"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.2,
      "reviews": 72,
      "image": "https://images.unsplash.com/photo-1566475664769-58f79d50457f?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8TWVuJ3MlMjBSZWxheGVkJTIwRml0JTIwSmVhbnN8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-102",
      "name": "Women’s Denim Shorts",
      "category": "clothing",
      "price": 3499,
      "colors": ["blue", "white"],
      "sizes": ["XS", "S", "M", "L"],
      "rating": 4.3,
      "reviews": 65,
      "image": "https://images.unsplash.com/photo-1651694558313-fdfc4ee862ba?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V29tZW4lRTIlODAlOTlzJTIwRGVuaW0lMjBTaG9ydHN8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-103",
      "name": "Smart Coffee Maker",
      "category": "home",
      "price": 4999,
      "colors": ["black", "silver"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 130,
      "image": "https://images.unsplash.com/photo-1565452344518-47faca79dc69?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8U21hcnQlMjBDb2ZmZWUlMjBNYWtlcnxlbnwwfHwwfHx8MA%3D%3D",
      "inStock": true
    },
    {
      "id": "prod-104",
      "name": "Men's Bootcut Jeans",
      "category": "clothing",
      "price": 699,
      "colors": ["blue", "gray"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.0,
      "reviews": 58,
      "image": "https://images.unsplash.com/photo-1556361195-d970e3870013?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWVuJ3MlMjBCb290Y3V0JTIwSmVhbnN8ZW58MHx8MHx8fDA%3D",
      "inStock": true
    },
    {
      "id": "prod-105",
      "name": "Wireless Mouse Pad",
      "category": "electronics",
      "price": 2999,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.4,
      "reviews": 85,
      "image": "https://via.placeholder.com/300?text=Mouse+Pad",
      "inStock": true
    },
    {
      "id": "prod-106",
      "name": "Women’s Flannel Shirt",
      "category": "clothing",
      "price": 399,
      "colors": ["red", "blue", "green"],
      "sizes": ["S", "M", "L"],
      "rating": 4.3,
      "reviews": 70,
      "image": "https://via.placeholder.com/300?text=Flannel+Shirt",
      "inStock": true
    },
    {
      "id": "prod-107",
      "name": "Stainless Steel Blender",
      "category": "home",
      "price": 599,
      "colors": ["silver"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 110,
      "image": "https://via.placeholder.com/300?text=Blender",
      "inStock": true
    },
    {
      "id": "prod-108",
      "name": "Men's Straight Fit Jeans",
      "category": "clothing",
      "price": 799,
      "colors": ["blue", "black"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.2,
      "reviews": 68,
      "image": "https://via.placeholder.com/300?text=Straight+Jeans",
      "inStock": true
    },
    {
      "id": "prod-109",
      "name": "Smart Door Lock",
      "category": "electronics",
      "price": 14999,
      "colors": ["silver", "black"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 120,
      "image": "https://via.placeholder.com/300?text=Door+Lock",
      "inStock": true
    },
    {
      "id": "prod-110",
      "name": "Women’s Maxi Dress",
      "category": "clothing",
      "price": 499,
      "colors": ["black", "blue"],
      "sizes": ["S", "M", "L"],
      "rating": 4.4,
      "reviews": 80,
      "image": "https://via.placeholder.com/300?text=Maxi+Dress",
      "inStock": true
    },
    {
      "id": "prod-111",
      "name": "Ceramic Teapot",
      "category": "home",
      "price": 2999,
      "colors": ["white", "blue"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 95,
      "image": "https://via.placeholder.com/300?text=Teapot",
      "inStock": true
    },
    {
      "id": "prod-112",
      "name": "Men's Distressed Jeans",
      "category": "clothing",
      "price": 6999,
      "colors": ["blue", "black"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.1,
      "reviews": 62,
      "image": "https://via.placeholder.com/300?text=Distressed+Jeans",
      "inStock": true
    },
    {
      "id": "prod-113",
      "name": "Wireless Earphones",
      "category": "electronics",
      "price": 7999,
      "colors": ["black", "white"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 115,
      "image": "https://via.placeholder.com/300?text=Earphones",
      "inStock": true
    },
    {
      "id": "prod-114",
      "name": "Women’s Denim Jacket",
      "category": "clothing",
      "price": 3999,
      "colors": ["blue"],
      "sizes": ["S", "M", "L"],
      "rating": 4.3,
      "reviews": 75,
      "image": "https://via.placeholder.com/300?text=Women+Denim+Jacket",
      "inStock": true
    },
    {
      "id": "prod-115",
      "name": "Glass Mixing Bowl Set",
      "category": "home",
      "price": 399,
      "colors": ["clear"],
      "sizes": [],
      "rating": 4.7,
      "reviews": 100,
      "image": "https://via.placeholder.com/300?text=Mixing+Bowl+Set",
      "inStock": true
    },
    {
      "id": "prod-116",
      "name": "Men's Tapered Jeans",
      "category": "clothing",
      "price": 6299,
      "colors": ["blue", "gray"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.2,
      "reviews": 70,
      "image": "https://via.placeholder.com/300?text=Tapered+Jeans",
      "inStock": true
    },
    {
      "id": "prod-117",
      "name": "Smart Humidifier",
      "category": "home",
      "price": 6599,
      "colors": ["white"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 90,
      "image": "https://via.placeholder.com/300?text=Humidifier",
      "inStock": true
    },
    {
      "id": "prod-118",
      "name": "Women’s Athletic Leggings",
      "category": "clothing",
      "price": 499,
      "colors": ["black", "gray"],
      "sizes": ["XS", "S", "M", "L"],
      "rating": 4.4,
      "reviews": 85,
      "image": "https://via.placeholder.com/300?text=Leggings",
      "inStock": true
    },
    {
      "id": "prod-119",
      "name": "Wireless HDMI Transmitter",
      "category": "electronics",
      "price": 899,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.4,
      "reviews": 95,
      "image": "https://via.placeholder.com/300?text=HDMI+Transmitter",
      "inStock": true
    },
    {
      "id": "prod-120",
      "name": "Men's Ripped Jeans",
      "category": "clothing",
      "price": 6799,
      "colors": ["blue", "black"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.1,
      "reviews": 60,
      "image": "https://via.placeholder.com/300?text=Ripped+Jeans",
      "inStock": true
    },
    {
      "id": "prod-121",
      "name": "Bamboo Utensil Set",
      "category": "home",
      "price": 199,
      "colors": ["natural"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 80,
      "image": "https://via.placeholder.com/300?text=Utensil+Set",
      "inStock": true
    },
    {
      "id": "prod-122",
      "name": "Women’s Sweater Dress",
      "category": "clothing",
      "price": 5499,
      "colors": ["gray", "black"],
      "sizes": ["S", "M", "L"],
      "rating": 4.3,
      "reviews": 70,
      "image": "https://via.placeholder.com/300?text=Sweater+Dress",
      "inStock": true
    },
    {
      "id": "prod-123",
      "name": "Smart Air Fryer",
      "category": "home",
      "price": 12999,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.7,
      "reviews": 140,
      "image": "https://via.placeholder.com/300?text=Air+Fryer",
      "inStock": true
    },
    {
      "id": "prod-124",
      "name": "Men's Skinny Jeans",
      "category": "clothing",
      "price": 5999,
      "colors": ["black", "blue"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.0,
      "reviews": 55,
      "image": "https://via.placeholder.com/300?text=Skinny+Jeans",
      "inStock": true
    },
    {
      "id": "prod-125",
      "name": "Wireless VR Headset",
      "category": "electronics",
      "price": 29999,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 130,
      "image": "https://via.placeholder.com/300?text=VR+Headset",
      "inStock": true
    },
    {
      "id": "prod-126",
      "name": "Women’s Trench Coat",
      "category": "clothing",
      "price": 999,
      "colors": ["beige", "black"],
      "sizes": ["S", "M", "L"],
      "rating": 4.4,
      "reviews": 90,
      "image": "https://via.placeholder.com/300?text=Trench+Coat",
      "inStock": true
    },
    {
      "id": "prod-127",
      "name": "Stainless Steel Pressure Cooker",
      "category": "home",
      "price": 2999,
      "colors": ["silver"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 110,
      "image": "https://via.placeholder.com/300?text=Pressure+Cooker",
      "inStock": true
    },
    {
      "id": "prod-128",
      "name": "Men's Loose Fit Jeans",
      "category": "clothing",
      "price": 4799,
      "colors": ["blue", "gray"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.2,
      "reviews": 65,
      "image": "https://via.placeholder.com/300?text=Loose+Jeans",
      "inStock": true
    },
    {
      "id": "prod-129",
      "name": "Smart Baby Monitor",
      "category": "electronics",
      "price": 8999,
      "colors": ["white"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 100,
      "image": "https://via.placeholder.com/300?text=Baby+Monitor",
      "inStock": true
    },
    {
      "id": "prod-130",
      "name": "Women’s Crop Top",
      "category": "clothing",
      "price": 299,
      "colors": ["white", "black"],
      "sizes": ["S", "M", "L"],
      "rating": 4.3,
      "reviews": 60,
      "image": "https://via.placeholder.com/300?text=Crop+Top",
      "inStock": true
    },
    {
      "id": "prod-131",
      "name": "Ceramic Knife Set",
      "category": "home",
      "price": 399,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 95,
      "image": "https://via.placeholder.com/300?text=Knife+Set",
      "inStock": true
    },
    {
      "id": "prod-132",
      "name": "Men's Athletic Jeans",
      "category": "clothing",
      "price": 6499,
      "colors": ["blue", "black"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.3,
      "reviews": 70,
      "image": "https://via.placeholder.com/300?text=Athletic+Jeans",
      "inStock": true
    },
    {
      "id": "prod-133",
      "name": "Wireless Gaming Headset",
      "category": "electronics",
      "price": 8599,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 120,
      "image": "https://via.placeholder.com/300?text=Gaming+Headset",
      "inStock": true
    },
    {
      "id": "prod-134",
      "name": "Women’s Jumpsuit",
      "category": "clothing",
      "price": 599,
      "colors": ["black", "blue"],
      "sizes": ["S", "M", "L"],
      "rating": 4.4,
      "reviews": 80,
      "image": "https://via.placeholder.com/300?text=Jumpsuit",
      "inStock": true
    },
    {
      "id": "prod-135",
      "name": "Glass Water Pitcher",
      "category": "home",
      "price": 299,
      "colors": ["clear"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 85,
      "image": "https://via.placeholder.com/300?text=Water+Pitcher",
      "inStock": true
    },
    {
      "id": "prod-136",
      "name": "Men's Vintage Jeans",
      "category": "clothing",
      "price": 6999,
      "colors": ["blue", "gray"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.2,
      "reviews": 65,
      "image": "https://via.placeholder.com/300?text=Vintage+Jeans",
      "inStock": true
    },
    {
      "id": "prod-137",
      "name": "Smart Ceiling Fan",
      "category": "home",
      "price": 7890,
      "colors": ["white"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 110,
      "image": "https://via.placeholder.com/300?text=Ceiling+Fan",
      "inStock": true
    },
    {
      "id": "prod-138",
      "name": "Women’s Hooded Jacket",
      "category": "clothing",
      "price": 799,
      "colors": ["black", "gray"],
      "sizes": ["S", "M", "L"],
      "rating": 4.4,
      "reviews": 90,
      "image": "https://via.placeholder.com/300?text=Hooded+Jacket",
      "inStock": true
    },
    {
      "id": "prod-139",
      "name": "Wireless Trackpad",
      "category": "electronics",
      "price": 4999,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.4,
      "reviews": 85,
      "image": "https://via.placeholder.com/300?text=Trackpad",
      "inStock": true
    },
    {
      "id": "prod-140",
      "name": "Men's Stretch Jeans",
      "category": "clothing",
      "price": 599,
      "colors": ["blue", "black"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.3,
      "reviews": 75,
      "image": "https://via.placeholder.com/300?text=Stretch+Jeans",
      "inStock": true
    },
    {
      "id": "prod-141",
      "name": "Bamboo Serving Tray",
      "category": "home",
      "price": 299,
      "colors": ["natural"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 90,
      "image": "https://via.placeholder.com/300?text=Serving+Tray",
      "inStock": true
    },
    {
      "id": "prod-142",
      "name": "Women’s Sports Bra",
      "category": "clothing",
      "price": 399,
      "colors": ["black", "pink"],
      "sizes": ["S", "M", "L"],
      "rating": 4.4,
      "reviews": 80,
      "image": "https://via.placeholder.com/300?text=Sports+Bra",
      "inStock": true
    },
    {
      "id": "prod-143",
      "name": "Smart Water Leak Detector",
      "category": "electronics",
      "price": 5999,
      "colors": ["white"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 95,
      "image": "https://via.placeholder.com/300?text=Leak+Detector",
      "inStock": true
    },
    {
      "id": "prod-144",
      "name": "Men's Classic Jeans",
      "category": "clothing",
      "price": 599,
      "colors": ["blue", "black"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.2,
      "reviews": 70,
      "image": "https://via.placeholder.com/300?text=Classic+Jeans",
      "inStock": true
    },
    {
      "id": "prod-145",
      "name": "Ceramic Serving Platter",
      "category": "home",
      "price": 3999,
      "colors": ["white"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 100,
      "image": "https://via.placeholder.com/300?text=Serving+Platter",
      "inStock": true
    },
    {
      "id": "prod-146",
      "name": "Women’s Tank Top",
      "category": "clothing",
      "price": 199,
      "colors": ["white", "black"],
      "sizes": ["S", "M", "L"],
      "rating": 4.3,
      "reviews": 65,
      "image": "https://via.placeholder.com/300?text=Tank+Top",
      "inStock": true
    },
    {
      "id": "prod-147",
      "name": "Wireless Charging Dock",
      "category": "electronics",
      "price": 4999,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 90,
      "image": "https://via.placeholder.com/300?text=Charging+Dock",
      "inStock": true
    },
    {
      "id": "prod-148",
      "name": "Men's Slim Tapered Jeans",
      "category": "clothing",
      "price": 699,
      "colors": ["blue", "gray"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.2,
      "reviews": 68,
      "image": "https://via.placeholder.com/300?text=Slim+Tapered+Jeans",
      "inStock": true
    },
    {
      "id": "prod-149",
      "name": "Glass Storage Jar",
      "category": "home",
      "price": 1499,
      "colors": ["clear"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 85,
      "image": "https://via.placeholder.com/300?text=Storage+Jar",
      "inStock": true
    },
    {
      "id": "prod-150",
      "name": "Women’s Chino Pants",
      "category": "clothing",
      "price": 499,
      "colors": ["navy", "beige"],
      "sizes": ["S", "M", "L"],
      "rating": 4.3,
      "reviews": 70,
      "image": "https://via.placeholder.com/300?text=Chino+Pants",
      "inStock": true
    },
    {
      "id": "prod-151",
      "name": "Smart Light Bulb Set",
      "category": "electronics",
      "price": 3899,
      "colors": ["white"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 100,
      "image": "https://via.placeholder.com/300?text=Light+Bulb+Set",
      "inStock": true
    },
    {
      "id": "prod-152",
      "name": "Men's Carpenter Jeans",
      "category": "clothing",
      "price": 599,
      "colors": ["blue", "black"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.1,
      "reviews": 60,
      "image": "https://via.placeholder.com/300?text=Carpenter+Jeans",
      "inStock": true
    },
    {
      "id": "prod-153",
      "name": "Stainless Steel French Press",
      "category": "home",
      "price": 3299,
      "colors": ["silver"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 95,
      "image": "https://via.placeholder.com/300?text=French+Press",
      "inStock": true
    },
    {
      "id": "prod-154",
      "name": "Women’s Blazer",
      "category": "clothing",
      "price": 799,
      "colors": ["black", "navy"],
      "sizes": ["S", "M", "L"],
      "rating": 4.4,
      "reviews": 85,
      "image": "https://via.placeholder.com/300?text=Blazer",
      "inStock": true
    },
    {
      "id": "prod-155",
      "name": "Wireless Dash Cam",
      "category": "electronics",
      "price": 7999,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 110,
      "image": "https://via.placeholder.com/300?text=Dash+Cam",
      "inStock": true
    },
    {
      "id": "prod-156",
      "name": "Men's Work Jeans",
      "category": "clothing",
      "price": 699,
      "colors": ["blue", "gray"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.3,
      "reviews": 70,
      "image": "https://via.placeholder.com/300?text=Work+Jeans",
      "inStock": true
    },
    {
      "id": "prod-157",
      "name": "Ceramic Baking Dish",
      "category": "home",
      "price": 299,
      "colors": ["white"],
      "sizes": [],
      "rating": 4.6,
      "reviews": 90,
      "image": "https://via.placeholder.com/300?text=Baking+Dish",
      "inStock": true
    },
    {
      "id": "prod-158",
      "name": "Women’s Slip-On Shoes",
      "category": "clothing",
      "price": 1599,
      "colors": ["black", "white"],
      "sizes": ["6", "7", "8"],
      "rating": 4.4,
      "reviews": 80,
      "image": "https://via.placeholder.com/300?text=Slip-On+Shoes",
      "inStock": true
    },
    {
      "id": "prod-159",
      "name": "Smart Thermometer",
      "category": "electronics",
      "price": 4999,
      "colors": ["white"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 95,
      "image": "https://via.placeholder.com/300?text=Thermometer",
      "inStock": true
    },
    {
      "id": "prod-160",
      "name": "Men's Relaxed Straight Jeans",
      "category": "clothing",
      "price": 599,
      "colors": ["blue", "black"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.2,
      "reviews": 65,
      "image": "https://via.placeholder.com/300?text=Relaxed+Straight+Jeans",
      "inStock": true
    },
    {
      "id": "prod-161",
      "name": "Bamboo Salad Tongs",
      "category": "home",
      "price": 199,
      "colors": ["natural"],
      "sizes": [],
      "rating": 4.5,
      "reviews": 80,
      "image": "https://via.placeholder.com/300?text=Salad+Tongs",
      "inStock": true
    },
    {
      "id": "prod-162",
      "name": "Women’s Romper",
      "category": "clothing",
      "price": 4499,
      "colors": ["black", "blue"],
      "sizes": ["S", "M", "L"],
      "rating": 4.3,
      "reviews": 70,
      "image": "https://via.placeholder.com/300?text=Romper",
      "inStock": true
    },
    {
      "id": "prod-163",
      "name": "Wireless Power Strip",
      "category": "electronics",
      "price": 3999,
      "colors": ["black"],
      "sizes": [],
      "rating": 4.4,
      "reviews": 90,
      "image": "https://via.placeholder.com/300?text=Power+Strip",
      "inStock": true
    },
    {
      "id": "prod-164",
      "name": "Men's Slim Straight Jeans",
      "category": "clothing",
      "price": 6299,
      "colors": ["blue", "gray"],
      "sizes": ["28", "30", "32", "34", "36"],
      "rating": 4.2,
      "reviews": 68,
      "image": "https://via.placeholder.com/300?text=Slim+Straight+Jeans",
      "inStock": true
    },
]

  export default products;